# Use a Node.js base image
FROM node:20-slim

# Set the working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./

# Install all production dependencies (including Medusa packages, but excluding dev)
# We ensure ts-node is included if it's a prod dep or we install it explicitly
RUN npm install --omit=dev

# Copy all other application files (source, compiled, config)
COPY . .

# FIX 1: Create a temporary tsconfig for production compilation (to exclude tests).
RUN echo '{ "extends": "./tsconfig.json", "exclude": ["integration-tests", "**/*.spec.ts", "test"] }' > tsconfig.build.json

# FIX 2: Explicitly compile the backend using the TypeScript compiler (tsc).
# This compiles source into the required .medusa/server directory.
RUN npx tsc --project tsconfig.build.json --outDir .medusa/server

# Expose the default Medusa port
EXPOSE 9000

# FIX 3: Set the entry point to run the COMPILED JavaScript file directly.
# This bypasses the 'medusa start' script, which is the source of the Admin path check error.
# We explicitly call the compiled index.js file generated by the previous step.
# The server will now start in headless mode without checking for index.html.
ENTRYPOINT ["node", ".medusa/server/main.js"]